In [1]:
import math
import numpy as np
import torch

In [2]:
a1 = torch.tensor([[1, 1, 1], [2, 2, 2]])
s1 = torch.sum(a1, dim=1)
print(s1.shape)
s1.reshape((2,1))

torch.Size([2])


tensor([[3],
        [6]])

In [64]:
def softmax(x):
    a = torch.exp(t)
    b = torch.sum(torch.exp(t), dim=1)
    return a / b.reshape((a.shape[0], 1))

In [65]:
print(f'softmax = {softmax(a1)}')
print(f'sum = {torch.sum(softmax(a1))}')

softmax = tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])
sum = 2.0


In [66]:
x = torch.tensor([1.0589e-09, 6.5772e-02, 2.2230e-01, 2.2982e-07, 3.2202e-01, 9.9984e-01,
        3.3078e-03, 6.8753e-01, 3.4633e-06, 7.9059e-01])

In [68]:
print(f'softmax = {softmax(x)}')
print(f'sum {torch.sum(softmax(x), dim=1)}')

softmax = tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])
sum tensor([1., 1.])


In [63]:
x = [[1, 1, 1], [1, 1, 1]]
t = torch.tensor(x)
a = torch.exp(t)
b = torch.sum(torch.exp(t), dim=1)
# r2 =  a / b
# print(f'r2 = {r2}, r2.sum = {r2.sum()}')
r = a / b.reshape((a.shape[0], 1))
r.sum(dim=1)

tensor([1., 1.])

In [25]:
print(torch.sum(torch.exp(torch.tensor([1, 1, 1]))))
torch.exp(torch.tensor([1, 1, 1]))

tensor(8.1548)


tensor([2.7183, 2.7183, 2.7183])

In [36]:
print(torch.sum(torch.exp(torch.tensor([[1, 1, 1], [1, 1, 1]])), dim=1))
print(torch.exp(torch.tensor([1, 1, 1])))

tensor([8.1548, 8.1548])
tensor([2.7183, 2.7183, 2.7183])


In [3]:
from torch import nn
import torch.nn.functional as F

class Network(nn.Module):
    def __init__(self):
        super().__init__()
        
        # fc1 - Input layer
        self.fc1 = nn.Linear(784, 128)

        # relu
        self.relu1 = nn.ReLU()
        
        # fc2- Hidden layer 1
        self.fc2 = nn.Linear(128, 64)
        
        # relu
        self.relu2 = nn.ReLU()
        
        # Output layer, 10 units - one for each digit
        self.output = nn.Linear(64, 10)
        
        # relu
        self.relu_output = nn.Softmax(dim=1)
        
    def forward(self, x):
        # Hidden layer with relu activation
        x = F.relu(self.fc1(x))
        # Hidden layer with relu activation
        x = F.relu(self.fc2(x))
        # Output
        x = F.relu(self.output(x))
        
        return x

In [5]:
model = Network()
model

Network(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (relu2): ReLU()
  (output): Linear(in_features=64, out_features=10, bias=True)
  (relu_output): Softmax(dim=1)
)